### PR TITLE
Add a JunOS family test for future use.

### PR DESCRIPTION
**Pull request by joval**
We want to reserve IDs for the test and state, which we'll use to develop some vulnerability definitions.

### CODE REVIEW

**Comment by wmunyan** [comment]
David, 
If you want to create a new set of elements for your JunOS tests, please create them with an id attribute value using a joval-based namespace, such as "oval:com.jovalcm:obj:1", set the version attribute to "0", and we can process them.  They will get generated new "org.cisecurity" id's based on the current state of the repository when the PR is processed.

Thanks!
-Bill M.

**Comment by joval** [comment]
Hi Bill,

I've done what you asked (I think?)...

Can you tell me the corresponding CIS IDs once you've merged them?  I'm going to be using these in templates for content generation.

Thanks,
--David Solin

**Comment by wmunyan** [comment]
David, 
Yup changes look sane.  You should get an email from GitHub when the PR gets merged that should have the new IDs in it, but we'll follow up as well.
Cheers, 
-Bill M.

**Comment by solind** [comment]
So… should all submissions use a distinct (non-CIS) namespace?  And, do the internal cross-references need to be consistent over time, or only at the time of submission?  This isn't documented in CONTRIBUTING.md.

Eventually I hope to add a bunch of objects that are going to get referenced by templates that will be used by some OVAL content generators we’re working on.  We have the ability to grab the next sequential cisecurity OVAL IDs from the repository, but we could also use our own namespace.  If all submissions always need to have their own non-CIS namespace IDs, (a) that should be documented, and (b) we will always have to process template changes and generated content submissions separately, because we’ll always have to update the templates with any CIS-assigned IDs.

Best regards,
—David Solin

**Comment by wmunyan** [comment]
Right now, yes, all new element submissions are required to be in the non-CIS namespace, so we can keep track of the latest IDs on our side.  There'd definitely be Q/A issues if, say you grabbed the next available ID from the repo in your process, then we processed a PR from a separate submitter and generated that ID.  Then once you submit your PRs, those IDs would then overwrite the initial PRs submission.

**Comment by solind** [comment]
I understand the concern, but at least Git is designed to spot file conflicts.  If I were to add 1000 new definitions using my own namespace, won’t re-mapping all the IDs present its own QA challenges?

**Comment by wmunyan** [comment]
In case you didnt see them:
Your new test is oval:org.cisecurity:tst:1207, object is oval:org.cisecurity:obj:315, and state is oval:org.cisecurity:ste:961.

More to follow on the conversation.  Maybe we should move that to an issue to keep track of it?
Cheers, 
-B

**Comment by solind** [comment]
Sure, thanks!

**Pull request merged**
