### PR TITLE
Windows 10 LTSB inventory

### PR DESCRIPTION
**Pull request by kemanik**

### CODE REVIEW

**Comment by kemanik** [comment]
I don’t see a fundamental difference and it makes no sense to change now, because it works in current version.

**Comment by edayton** [comment]
Good morning! Please see the error presented when processing. Thank you!
#### Warning prune_unchanged_elements not currently doing anything.  This submis
sion could update elements that didn't actually change.

  ---- Number of changed elements to process: 20

 + 3: Checking correctness of definition metadata
   +++ Number of definitions in this update: 6
   ++++ Definition ID oval:ru.altx-soft.win:def:43541 is NOT valid:
    - New definitions must have a status of INITIAL SUBMISSION
   ++++ Definition ID oval:ru.altx-soft.win:def:58706 is NOT valid:
    - New definitions must have a status of INITIAL SUBMISSION
   ++++ Definition ID oval:ru.altx-soft.win:def:37232 is NOT valid:
    - New definitions must have a status of INITIAL SUBMISSION
   ++++ Definition ID oval:ru.altx-soft.win:def:58707 is NOT valid:
    - New definitions must have a status of INITIAL SUBMISSION
   ++++ Definition ID oval:ru.altx-soft.win:def:58708 is NOT valid:
    - New definitions must have a status of INITIAL SUBMISSION
   ++++ Definition ID oval:ru.altx-soft.win:def:58705 is NOT valid:
    - New definitions must have a status of INITIAL SUBMISSION

   ++++ Definition Metadata is Invalid.  Exiting...

**Comment by rakshitkitchloo** [comment]
Hi Maria,
@kemanik 

From couple of months, Windows Vulnerability OVAL content is not published here. Do you have any update on that?

Thanks and Regards,
Rakshit Kitchloo

**Comment by solind** [comment]
Hi @kemanik, I think the current version does not always work.  For example, we have seen instances where there have been multiple CurrentBuild values that map to the same releaseId.  For example, one number might be used for early/preview releases, and that number +1 gets used for the LTS.

Since the releaseId was introduced with Windows 10, and it correlates exactly with the YYMM release ID used by Microsoft, it seems better to use it.

**Comment by edayton** [comment]
Hello! Please see the error when processing this PR.
+ 4: Schema validating changes...
   Schema validation failed:
       Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5}submitted',
attribute 'date': '2019-10-091T17:55:11' is not a valid value of the atomic typ
e 'xs:dateTime'.
### Offending file C:\OVALRepo\repository/definitions/inventory/oval_ru.altx-so
ft.win_def_43541.xml

**Comment by kemanik** [comment]
@DavidRies @solind Hi. Could you show an example when CurrentBuild doesn't work. In Windows 10 1507 Build 10240 for example there is no field ReleaseID at all.
image1571124120139

Build number also used in versions of system files.

**Comment by DavidRies** [comment]
HI @kemanik,

This came to our attention when we discovered that the inventory definition for Windows 10 1803 was checking for CurrentBuild 17133 ([see this change](https://github.com/CISecurity/OVALRepo/pull/1741/files#diff-3db6e3e9a1fab91864657555af6de18b)). 1803 should be checking for 17134 ([see docs here](https://docs.microsoft.com/en-us/windows/release-information/)). But, it turns out that 1803 was originally released as a "Spring Creators Update" using 17133. This is easy to miss because: a) it was correct when the definition was created; and b) the mapping between release and build number is not obvious.

We were going to simply fix the build number in this definition, but then we found the ReleaseId and that seemed preferable because it was simpler and seemingly more reliable.

So, in at least one case, Microsoft seems to have changed the CurrentBuild for a ReleaseId.

However, we were not aware that 10240 does not include a ReleaseId.

Perhaps we should use both, OR'ing them together for each platform. Then we have our bases covered, e.g.:

- OR:
  - ReleaseId equals targeted release id
  - CurrentBuild equals corresponding build number

What do you think?

-David

**Comment by kemanik** [comment]
Ok, @DavidRies, let this request would be committed and then you can add alternative check with OR operator.

**Pull request merged**
