### PR TITLE
2019 Firefox and Thunderbird CVE

### PR DESCRIPTION
**Pull request by glugod-aurea**

### CODE REVIEW

**Comment by DavidRies** [comment]
@glugod-aurea, it looks like some of the definitions in this content contain duplicate <affected> element values. 

### Definitions with this issue:

- [oval:org.cisecurity:def:7100](https://github.com/CISecurity/OVALRepo/blob/cd6e53d5798538f6a54670d2669fac15b6fec2aa/repository/definitions/vulnerability/oval_org.cisecurity_def_7100.xml)
- [oval:org.cisecurity:def:7106](https://github.com/CISecurity/OVALRepo/blob/cd6e53d5798538f6a54670d2669fac15b6fec2aa/repository/definitions/vulnerability/oval_org.cisecurity_def_7106.xml)

### Examples (XML excerpts from above):
````
<definition xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" class="vulnerability" id="oval:org.cisecurity:def:7106" version="2">
  <metadata>
    <title>Multiple vulnerabilities in Mozilla Firefox before 69, Firefox ESR before 60.9, Firefox ESR before 68.1, Thunderbird before 68.1, and Thunderbird before 60.9</title>
    <affected family="windows">
      ...
      <product>Mozilla Thunderbird</product>
      <product>Mozilla Thunderbird</product>
      <product>Mozilla Firefox ESR</product>
      <product>Mozilla Firefox ESR</product>
    </affected>
...
</definition>

<definition xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" class="vulnerability" id="oval:org.cisecurity:def:7100" version="2">
  <metadata>
    <title>The Firefox installer allows Firefox to be installed to a custom user writable location, leaving it unprotected from manipulation by unprivileged users or malware.</title>
    <affected family="windows">
      ...
      <product>Mozilla Firefox ESR</product>
      <product>Mozilla Firefox ESR</product>
    </affected>
...
</definition>
````

### Severity: High
This is a significant issue because it causes packages to fail schema validation and that could prevent scanners from being able to run repository content.

````
SAX Error: Duplicate unique value [Mozilla Thunderbird] declared for identity constraint of element "affected".
SAX Error: Duplicate unique value [Mozilla Firefox ESR] declared for identity constraint of element "affected".
SAX Error: Duplicate unique value [Mozilla Firefox ESR] declared for identity constraint of element "affected".
Schema validation failed; error count: 3
````

### Resolution

Are you available and will to resolve this:

1. Check for any other issues like this
2. Fix these and submit the fixes
3. Review your process to avoid this in the future
4. Ensure you schema validate submissions before submitting to avoid other validation-identifiable issues going forward

-David Ries

**Comment by glugod-aurea** [comment]
I'll fix these.

Glenn

**Comment by DavidRies** [comment]
Awesome! I've also reached out the CIS team that QAs submissions to find out why this wasn't caught in the QA/review process. At a minimum, we need to schema validate all submissions before including them.

**Comment by glugod-aurea** [comment]
I've ran validation scripts before creating a pull-request (build_oval_definitions_file with -v) and this was not caught. The script needs adjustments imho to support this case.

**Comment by DavidRies** [comment]
That's interesting. I validated using Joval and it picked up this issue. Just tried using the Repo scripts and--just like you said--it passed schema validation. Good catch! We'll have to investigate to figure out why.

**Comment by wmunyan** [comment]
Looking at the schemas included in the repo (in `oval_schemas/5.11.2`), within the `all-oval-definitions.xsd` there is a `redefine` element in there which seems to modify the `AffectedType` to this:
```
<xsd:element maxOccurs="unbounded" minOccurs="0" name="affected" type="oval-def:AffectedType"/>
```
I think that might be overriding the element definition in `oval-definitions-schema.xsd`, where the uniqueness validation is defined.

Could the `redefine` bits be causing the elimination of the uniqueness verification?

**Comment by glugod-aurea** [comment]
https://github.com/CISecurity/OVALRepo/pull/1773 for the fix

**Comment by DavidRies** [comment]
@wmunyan, yes that override looks like the problem. Great catch. I will confirm and fix.

**Pull request merged**
