### PR TITLE
Removed reliance on lib_repo from lib_oval

### PR DESCRIPTION
**Pull request by GunnarEngelbach**
This change is a slight reduction in functionality but means that lib_oval now has no requirements beyond a straight Python3.  That's not enough for repository management, but might make it easier for other usage.

Means making a slight change to oval_decomposition and rebuilt the API docs to match.

### CODE REVIEW

**Comment by DavidRies** [comment]
Hi Gunnar,

One concern I have about this script is that constructRelativeFilePath makes assumptions about the file organization of the repo. Our plan was to consolidate all assumptions about the repo org in lib_repo.py so that if/when we change the repo org, we can just change methods in lib_repo.py. 

If you think that's valuable, you might consider adding methods in lib_repo.py to create paths for you if there aren't already methods that you need in there.

-David

**Comment by GunnarEngelbach** [comment]
I agree.

I only did this for expediency in the moment, and to make it so lib_oval 
ended up with no dependencies on anything other than Python3.  Moving 
that into lib_repo would be the next step.

**Comment by GunnarEngelbach** [comment]
Moved the filepath determination into lib_repo, along with the necessary methods to be able to generate that path.  Removed that functionality from lib_oval and updated oval_decompose to use the changes.

Updated the API documentation to match.

**Comment by GunnarEngelbach** [comment]
Added the start for the find_affected script, which is intended to be usable for both file submissions and via pull requests.  Committing now in case I don't get a chance to keep working on it right away.

**Pull request merged**
