### PR TITLE
Kemanik comment fix

### PR DESCRIPTION
**Pull request by kemanik**
Comments in tests and in criterion are the same. Comments were added in interior criteria and they were removed from external criteria with operator="and".

### CODE REVIEW

**Comment by wmunyan** [comment]
Hi Maria, I was wondering if you might be able to merge this pull request into an updated pull from the repo.  GitHub is telling me there are conflicts in the PR, and they need to be resolved manually.  Normally I can do this without issue, but this PR is indicating almost 2000 conflicts.  Doing that manually would take a little too much time, so if there's a way we can work to get your PR limited in the number of conflicts, I'm happy to try and help.
Thanks, 
-Bill M.

**Comment by kemanik** [comment]
Hello,
How can I do this? I could pull request with update from the repo only into master branch. Then I try to merge master branch and this one and have "Can’t automatically merge"

**Comment by kemanik** [comment]
I'll do the new pull request

**Comment by kemanik** [comment]
See https://github.com/CISecurity/OVALRepo/pull/341

**Pull request closed without merging**
