### PR TITLE
Oval submission for HP-UX for Nov' 2015

### PR DESCRIPTION
**Pull request by jaikumark**
Oval definitions for HP-UX 11.23 for advisories published in Oct/Nov 2015

### CODE REVIEW

**Comment by wmunyan** [comment]
Hello, it looks like some of the definitions have incorrect metadata.  Some definitions are utilizing a HP ID syntax (indicating to me that these are new definitions) but the version is set to a non-zero value.  These should be version="0".

Also, any new definitions should contain metadata indicating a status of INITIAL SUBMISSION.

If these are updates, use the actual definition IDs with the existing version information, and update the status metadata.

Cheers, 
-Bill M.

**Comment by jaikumark** [comment]
Hi, I've corrected the metadata and committed the same.

Thanks & Regards
-Jai

**Comment by jaikumark** [comment]
Hi, the metadata has been updated and committed.

Thanks & Regards
-Jai

**Comment by wmunyan** [comment]
Jai, 
The following definitions still have non-zero version numbers:
oval:com.hp.temp.oval:def:20151103
oval:com.hp.temp.oval:def:20151104
oval:com.hp.temp.oval:def:20151106

Also, many of the updated definitions do not contain the appropriate <modified> metadata.  If updating definitions, modification information must be included.  The OVAL Repository metadata schema rules still apply -- http://oval.mitre.org/repository/download/schema/oval-repository-metadata-schema.xsd

Thanks, 
-Bill M.

**Pull request closed without merging**
