### PR TITLE
Sergey Artykhov New Patch DSA EOL typo3

### PR DESCRIPTION
**Pull request by SergeyArtykhov**

### CODE REVIEW

**Comment by wmunyan** [comment]
Sergey, 
Sorry to have to do this, but could you please replace the ":" in your filenames with "_"?  The box I use to process PRs is a Windows box and cannot handle the ":" in the filenames when pulling the request down to my machine for validation.
Thanks very much!
-Bill M.

**Comment by SergeyArtykhov** [comment]
Completed.

**Comment by wmunyan** [comment]
Thanks Sergey -- It looks like the 2 states still have some ":" in there:
ste:4991, and 
nix:ste_4992

Cheers, 
-Bill M.

**Comment by SergeyArtykhov** [comment]
Fixed.

**Pull request merged**
