### PR TITLE
A few library changes and a start on the comprehensive QA script

### PR DESCRIPTION
**Pull request by GunnarEngelbach**
Started a comprehensive QA script "submission_qa.py" -- defined all the major steps that correspond to https://github.com/CISecurity/OVALRepo/issues/34 but did not finish the coding for a number of them.

I hope to get back to this later today, but can't count on it, so here's what I have so far.

### CODE REVIEW

**Comment by DavidRies** [comment]
Hi Gunnar, a couple comments:
- the documentation updates make it really hard to see the substantive diffs in each commit. going forward, I think we should put non-substantive changes (i.e. docs) in their own commit after substantive so we can more easily review the changes to scripts
- it looks like there are conflicts that need to be resolved...

**Comment by DavidRies** [comment]
Just a note of encouragement... I'm swamped the next few days on a critical project and psyched you're tackling this one! If there's anything you want from me just assign me a task and I'll try.

**Comment by GunnarEngelbach** [comment]
There are a number of actions that need to be taken that I'm trying to 
tackle one-by-one, adding the functions to the lib_* files as I go.

If anybody else can tackle some of those functions, that would be helpful.

In particular (and refer to 
https://github.com/CISecurity/OVALRepo/issues/34 for more details on any 
of these):
   * Determine the next available CIS OVALID for any submitted element 
that is not already using one
         (should be simple to do by taking advantage of indeces in 
lib_search)

   * Determine if the version needs to be incremented and increment it 
as well as all affected elements
     (needs to account for the possibility that there is more than one 
updated element in the submission that likely are children of the same 
elements already in the repository, but those affected elements should 
only be incremented once)

   * Determine if a submitted definition changes any of the existing 
metadata

   * For a definition, verify that the metadata is complete and accurate

   * Determine if a changed file does not actually represent any 
meaningful changes to the element

   * Put the method get_min_oval_version.determine_def_min_version() 
into one of the libraries and fix the exception it is throwing:
    lxml.etree.XMLSyntaxError:  XML declaration allowed only at the 
start of the document, line 14 column 22


If anybody wants to take any of these on, please let me know so we don't 
duplicate efforts and can coordinate necessary parameters/return types

**Comment by GunnarEngelbach** [comment]
Oh, and one other:  use the lib_search indeces to determine if the update will result in any orphaned elements

**Pull request closed without merging**
