### PR TITLE
#1572 fix several url typos of Mitre-Links

### PR DESCRIPTION
**Pull request by Memnarch**
This Pullrequest fixes several typos in Mitre Urls and changes the protocol from http to https.

Changes:

cve.mkitre -> cve.mitre
www.cve.mitre -> cve.mitre
http://cve.mitre -> https://cve.mitre

### CODE REVIEW

**Comment by JasonBraun78** [comment]
Hey Memnarch, 

We are receiving this error when trying to process this pull request:

   ++++ Definition Metadata is Invalid.  Exiting...

We are still trying to determine the issue on why, if there is anything on your end you can think of.  Please review your repo and let us know.  

Cheers.

**Comment by Memnarch** [comment]
I'll look into that

**Comment by JasonBraun78** [comment]
Here is a snippet of the error(s):

Maybe this will help you identify the issue as other PR's are processing correctly.  Do you happen to know which file in production is causing the oval-generation to fail?

    ++++ Definition ID oval:org.mitre.oval:def:94 is NOT valid:
    - Last status change (INVALID) does not match definition status (ACCEPTED)
   ++++ Definition ID oval:org.mitre.oval:def:61 is NOT valid:
    - Last status change (INVALID) does not match definition status (ACCEPTED)
   ++++ Definition ID oval:org.mitre.oval:def:179 is NOT valid:
    - Last status change (INVALID) does not match definition status (ACCEPTED)
   ++++ Definition ID oval:org.mitre.oval:def:158 is NOT valid:
    - Last status change (INVALID) does not match definition status (ACCEPTED)
   ++++ Definition ID oval:org.cisecurity:def:5611 is NOT valid:
    - Last status change (INVALID) does not match definition status (INITIAL SUB
MISSION)
   ++++ Definition ID oval:org.cisecurity:def:5613 is NOT valid:
    - Last status change (INVALID) does not match definition status (INITIAL SUB
MISSION)
   ++++ Definition ID oval:org.cisecurity:def:5616 is NOT valid:
    - Last status change (INVALID) does not match definition status (INITIAL SUB
MISSION)
   ++++ Definition ID oval:org.mitre.oval:def:10 is NOT valid:
    - Last status change (INVALID) does not match definition status (ACCEPTED)

   ++++ Definition Metadata is Invalid.  Exiting...

**Comment by DavidRies** [comment]
Hi @JasonBraun78, it sounds like this is a QA script that checks the metadata of submissions to ensure it confirms to the repository's requirements. Is that right?

One issue is that these requirements don't see to be publicly documented. For example, I know there are expectations around version numbers, status, and etc. I would expect to find them here, but there's nothing: https://github.com/CISecurity/OVALRepo/blob/master/CONTRIBUTING.md

Are these requirements documented somewhere? If not, could you add them to that page?

**Pull request merged**
