### PR TITLE
Windows 10 Inventory Improvements

### PR DESCRIPTION
**Pull request by DavidRies**
I've revised the Windows 10 Inventory definitions to:

- consistently use extend defs for base windows family test, windows 10, x64, x86
- eliminate duplicate tests and fix references to all use the same definition for the same platform
- clarify titles when windows 10 version is missing
- change windows release version tests to use ReleaseId vs build number

### CODE REVIEW

**Comment by rakshitkitchloo** [comment]
Hi David,

From couple of months, Windows Vulnerability OVAL content is not published here. Do you have any update on that?

Thanks and Regards,
Rakshit Kitchloo

**Comment by kemanik** [comment]
@wmunyan Tell me please why don't you rise versions after commit acceptance? It's not the first time! For example oval:org.cisecurity:tst:4690 still has 7 version but object and comment were changed.

**Comment by wmunyan** [comment]
Hi @kemanik , I apologize for this one, I know its not the first time this has happened.  Unfortunately I am not seeing a pattern as to when it's happening to know where to make the fix in the script.  We'll keep doing our spot checking on PRs to make sure versions are being updated appropriately and if we spot a pattern, we'll make the fix ASAP.

In the meantime, I've updated the reference `oval:org.cisecurity:tst:4690` to version `8`.

**Comment by kemanik** [comment]
Ok, @wmunyan, then check all test from this 8 commits.

**Pull request merged**
