### PR TITLE
New Debian patches

### PR DESCRIPTION
**Pull request by kemanik**

### CODE REVIEW

**Comment by edayton** [comment]
Thanks for your submission to the OVAL repository.  In executing the QA process, one of our operations team members (Ed) came across an issue where some of the OVAL IDs referenced in the XML file are not fully referenced in other areas of the document.  For example, the <fileset_test> with an ID of "oval:com.hp.temp.oval:tst:201805042" makes reference to an object with ID "oval:com.hp.temp.oval:obj:201805041", however, that object ID is not present as a <fileset_object> further down in the <objects> section.  A second missing object we discovered is ID "oval:com.hp.temp.oval:obj:201805046".
 
Could you please take a look at your submission file, and ensure all ID references are present?  Once you've made any necessary corrections, please email us the updated file and we will re-process.

**Comment by kemanik** [comment]
@edayton I can't understand where did you find such tests and objects in my commit.

**Comment by edayton** [comment]
It seems to be related to the item below:
oval.ru.altx-soft.nix:obj:17627

**Comment by edayton** [comment]
Thank you!!

**Pull request merged**
