### PR TITLE
further improvements for the automatic generation of OVAL content from NVD

### PR DESCRIPTION
**Pull request by TudorCiochina**
Comments added, code cleanup and new options for the content generation.
--clean-cpe - removes the extra chars from the NVD version
--correct-NVD-product - replaces the product from the NVD CPE string, this comes very handy when scanning a custom RPM based distribution
--blacklist-cpe - skips the CPE if it contains a certain string

Left to do:
- don't add double content, don't add objects and states already present

### CODE REVIEW

**Comment by DavidRies** [comment]
Hi Tudor84,

Generally speaking, you should re-use tests, definitions and variables that already exist. States should only be reused if they are referenced by the same object. 

-David

**Comment by athiasjerome** [comment]
@DavidRies could you please kindly clarify why "States should only be reused if they are referenced by the same object."?
Thanks

**Comment by JovalComplianceNow** [comment]
Historically, we’ve prioritized ease of content authoring and maintenance over reducing the repo size. One guideline intended to make content easier to maintain is “States should only be reused if they are referenced by the same object.”

The general idea is that just because two states have the same entities, attributes, values, etc. doesn’t mean they “mean the same thing” or are interchangeable. If I want to revise one, I may not want to revise the other. Their meaning becomes much more specific when combined with a specific object. 

For example, a registry value of 1 could mean that feature foo is enabled when combined with the registry object that points to the “foo enabled” key. And, an identical registry value of 1 could mean that feature bar is enabled when combined with the registry object that points to the “bar enabled” key. 

We could deduplicate these states, but it would make content maintenance a bit messier. Imagine we realized that the proper “foo enabled” state value should be “true” and not the integer 1. I’d like to revise the current state and increment the @version. That way I have a nice version history and it fixes this issue for other tests that refer to this state. But, I would have to create a new state with a new @id and an @version=1 because revising this state would break the “bar enabled” test. If I want to be a model repo citizen, I would review all tests that refer to current state, identify the ones that also refer to the same object and update all of those to refer to the new object.

However, if states are only be reused when they are referenced by the same object, I can simply fix the state and increment the @version. 

It’s a general guideline and may not make sense in every situation, but that was the train of thought that led me to supporting the guideline.

These guidelines are always up for reconsideration.

**Comment by DavidRies** [comment]
Historically, we’ve prioritized ease of content authoring and maintenance over reducing the repo size. One guideline intended to make content easier to maintain is “States should only be reused if they are referenced by the same object.”

The general idea is that just because two states have the same entities, attributes, values, etc. doesn’t mean they “mean the same thing” or are interchangeable. If I want to revise one, I may not want to revise the other. Their meaning becomes much more specific when combined with a specific object.

For example, a registry value of 1 could mean that feature foo is enabled when combined with the registry object that points to the “foo enabled” key. And, an identical registry value of 1 could mean that feature bar is enabled when combined with the registry object that points to the “bar enabled” key.

We could deduplicate these states, but it would make content maintenance a bit messier. Imagine we realized that the proper “foo enabled” state value should be “true” and not the integer 1. I’d like to revise the current state and increment the @version. That way I have a nice version history and it fixes this issue for other tests that refer to this state. But, I would have to create a new state with a new @id and an @version=1 because revising this state would break the “bar enabled” test. If I want to be a model repo citizen, I would review all tests that refer to current state, identify the ones that also refer to the same object and update all of those to refer to the new object.

However, if states are only be reused when they are referenced by the same object, I can simply fix the state and increment the @version.

It’s a general guideline and may not make sense in every situation, but that was the train of thought that led me to supporting the guideline.

These guidelines are always up for reconsideration.

**Pull request closed without merging**
