### PR TITLE
Vulnerability content for HP_UX April 2016

### PR DESCRIPTION
**Pull request by chavalis**
Vulnerability content for HP_UX April 2016

### CODE REVIEW

**Comment by JasonBraun78** [comment]
This PR seems to be missing the file for {{oval:com.hp.temp.oval:ste:20160401}}.  Could you please add this file to the PR?
Thanks
-Bill M.

**Comment by chavalis** [comment]
Hi Bill, 
I will give a new PR with the changes.

Thanks,
Shruti

**Comment by chavalis** [comment]
Hi Bill,
I have created a new PR #323 (branch hpux_april16) for HP-UX April 2016. Please verify and merge.

Thanks,
Shruti

**Comment by wmunyan** [comment]
Shruti, 
Thanks for the update.  I will close this pull request in favor of #323.
Cheers, 
-Bill M.

**Pull request closed without merging**
